### ISSUE TITLE
Python 3.6で動かない (Multiprocessing周りのエラー)

### ISSUE THREAD

**Issue by kyuridenamida** [kyuridenamida/atcoder-tools#14]

**Comment by kyuridenamida** [comment]
```
/home/kmikami/.pyenv/versions/general/bin/python ./AtCoderClient.py arc001 --without-login
Traceback (most recent call last):
  File "./AtCoderClient.py", line 105, in <module>
    prepare_workspace(args.contestid, without_login)
  File "./AtCoderClient.py", line 91, in prepare_workspace
    p.map(prepare_procedure, [(atcoder, pid, url) for pid, url in plist.items()])
  File "/home/kmikami/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kmikami/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/home/kmikami/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/home/kmikami/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/kmikami/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

Process finished with exit code 1
```

**Comment by kyuridenamida** [comment]
これはAtCoderのインスタンスを並列化したい関数の引数に渡してるから起きてる可能性が高そう
