### ISSUE TITLE
pypi版だとatcodertools.tomlがin_example_formatやout_example_formatに対応していない

### ISSUE THREAD

**Issue by dbftdiyoeywga** [kyuridenamida/atcoder-tools#149]
## 環境
```
$ python3 -V
Python 3.6.8
$ python3 -m pip freeze | grep atcoder
atcoder-tools==1.1.4
```

## 状況
* readmeから該当箇所をコピーしatcodertools.tomlを作成
* `atcoder-tools get abc136`で以下のようなエラー
```
[user Comp]$ atcoder-tools gen abc136
2019-08-18 03:38:56,248 INFO: Going to load /home/user/.atcodertools.toml as config
Traceback (most recent call last):
  File "/home/user/.local/bin/atcoder-tools", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/atcodertools/atcoder_tools.py", line 55, in main
    envgen_main(prog, args)
  File "/home/user/.local/lib/python3.6/site-packages/atcodertools/tools/envgen.py", line 289, in main
    config = get_config(args)
  File "/home/user/.local/lib/python3.6/site-packages/atcodertools/tools/envgen.py", line 221, in get_config
    return _load(USER_CONFIG_PATH)
  File "/home/user/.local/lib/python3.6/site-packages/atcodertools/tools/envgen.py", line 215, in _load
    return Config.load(f, args)
  File "/home/user/.local/lib/python3.6/site-packages/atcodertools/config/config.py", line 57, in load
    etc_config=EtcConfig(**etc_config_dic)
TypeError: __init__() got an unexpected keyword argument 'in_example_format'
```

## その他
githubをcloneしたところ問題なかった
`etc_config.py`について
~pip~pypiは`0a5a9aa756565481306ee49773518c1a4c1ada76`のものが含まれているように見える
githubでホストされている現行の版も1.1.4なので少し混乱した

**Comment by kyuridenamida** [comment]
in_example_format / out_example_formatの変更は1.1.5から対応予定です。
これは僕が1.1.5を長らくリリースし忘れていたことに起因します。今からリリースします。すみません。

**Comment by kyuridenamida** [comment]
混乱させてしまい大変申し訳無かったです。今ようやくリリースしました。再度`pip install atcoder-tools`して頂けますか?
https://github.com/kyuridenamida/atcoder-tools/pull/152

**Comment by kyuridenamida** [comment]
再現のしやすい丁寧な問題報告をありがとうございました。一旦閉じますが解決してないようでしたら再度Reopenしてください。

**Comment by dbftdiyoeywga** [comment]
pypiからインストールしたら1.1.5で、readme通りの動作しました
素早い対応ありがとうございました
