### ISSUE TITLE
言語アップデートへの対応

### ISSUE THREAD

**Issue by nu50218** [kyuridenamida/atcoder-tools#190]
例えばC++でsubmit機能が使えなくなっていて、[atcodertools/common/language.py](https://github.com/kyuridenamida/atcoder-tools/blob/master/atcodertools/common/language.py)をアップデートする必要があると思います（他にも修正する箇所はありますか？）。またC++だけでなくJavaなども正規表現にマッチしないようになっているようなので、すべての言語を調べなきゃいけないようです。
ちなみに僕の出したGoのサポートのPR #181 は動いてることが確認できました。

**Comment by nu50218** [comment]
テストの環境も変える必要があるかもしれないですね

**Comment by s-higuma** [comment]
Pythonでもsubmitでエラーが発生しますが、[atcodertools/common/language.py:82](https://github.com/kyuridenamida/atcoder-tools/blob/1.1.6/atcodertools/common/language.py#L82) (v1.1.6)の`Python3`を`Python`に変更することで正常に動作しました。

**Comment by hiramekun** [comment]
C++に関してはこちらでプルリク作りましたけど、一括で変更する場合は閉じて構いません。
https://github.com/kyuridenamida/atcoder-tools/pull/191

**Comment by conao3** [comment]
最近このツールを使い初めた者です。
> submit機能が使えなくなっていて

というのは、submitを実行したときに次のようなエラーがでるということでしょうか。

```shell
$ atcoder-tools submit
2020-05-13 17:01:16,464 INFO: Loaded session from /home/conao/.local/share/atcoder-tools/cookie.txt
2020-05-13 17:01:16,996 INFO: Successfully Logged in using the previous session cache.
2020-05-13 17:01:16,996 INFO: If you'd like to invalidate the cache, delete /home/conao/.local/share/atcoder-tools/cookie.txt.
# in_1.txt ... PASSED 2 ms
# in_2.txt ... PASSED 3 ms
# in_3.txt ... PASSED 2 ms
Passed all test cases!!!
2020-05-13 17:01:17,742 INFO: Submitting ./main.cpp as cpp
Traceback (most recent call last):
  File "/home/conao/.anyenv/envs/pyenv/versions/3.8.2/bin/atcoder-tools", line 8, in <module>
    sys.exit(main())
  File "/home/conao/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/atcodertools/atcoder_tools.py", line 61, in main
    exit_program(submit_main(prog, args))
  File "/home/conao/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/atcodertools/tools/submit.py", line 117, in main
    submission = client.submit_source_code(
  File "/home/conao/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/atcodertools/client/atcoder.py", line 168, in submit_source_code
    language_number = language_select_area.find(
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by kyuridenamida** [comment]
皆様報告ありがとうございました。ようやく着手することができました。1.1.7にて修正されたと思います。

**Comment by pencilrocketman** [comment]
https://github.com/kyuridenamida/atcoder-tools/issues/190#issuecomment-627825722 is still remaining.
Check PR https://github.com/kyuridenamida/atcoder-tools/pull/208 and work around.
